# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review

# - id: doi:10.1016/j.csbj.2020.05.017
#   image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

# - id: doi:10.7554/eLife.32822
#   image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: doi:10.1093/neuonc/noae139
  type: paper
  description: sequential single-cell transcriptomics on 144 678 and spectral cytometry on over 2 million 
  immune cells encompassing 48 human gliomas to decipher their immune landscape.
  date: 2024-08-10
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/neuro-oncology/26/12/10.1093_neuonc_noae139/2/m_noae139_fig1.jpeg?Expires=1752181199&Signature=Hn8tHYuNCuLY13yI6DlofoArlQ2M0cwMGnM-rQLqI~fuFkGnnhFU3ptS5na0aTUUphNllMf2Fs-Hs9Oi93PyAYTfXxaFQjVULI4HPCMYlvNDmbAj9S01mFRHiFeID26BN5g6TI9rhabjA9C4wrQq7DqCieuX7DxCJOhCxRfNoEzffVXJp~vg8a2gihND~8FdHpq4LHj~gX3PI9QlSUXi-PUdaK4KHi4xr4~wy5bFmoffWYsLkyOYtEa3LTsw3TfML0X6QrY8an-jrxIFmWKdbHX5AC9LZjHzzngTBXX3VS5Tiwi954~OgfzwWLgB4FS4ZWY8cWfYkQH7tbY6-WDu8w__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  buttons:
    - type: manubot
      link: https://academic.oup.com/neuro-oncology/article/26/12/2239/7731280?login=true#496435539
    - type: source
      text: Manuscript Source
      link: https://academic.oup.com/neuro-oncology/article/26/12/2239/7731280?login=true#496435539
    - type: website
      link: https://www.mayo.edu/research/faculty/bhat-krishna-p-ph-d/bio-20561512
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1016/j.csbj.2020.05.017
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

